apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "keycloak.name" . }}-theme-dpn-portal
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "keycloak.selectorLabels" . | nindent 4 }}
    {{- include "keycloak.labels" . | nindent 4 }}
data:
  theme.properties: |
{{ .Files.Get "themes/dpn-portal/login/theme.properties" | indent 4 }}
  dpn-portal.css: |
{{ .Files.Get "themes/dpn-portal/login/resources/css/dpn-portal.css" | indent 4 }}
